<?php

require('vendor/autoload.php');

$access = false;

// API Youtube data
// Information about the API : https://developers.google.com/youtube/v3/code_samples/php#upload_a_video
// You will have to get your own 3 keys that are there :

$apiKey = "AIzaSyCM4hG8lmXY8sZDatjaElYZVfroUY2sKnE";
$clientID =  "971828143374-0d0fn2ao293mlcg99kvo42ibeqg03jcv.apps.googleusercontent.com";
$clientSecret = "z3V_PosIm0VhLkvUgRsgmcmy";

$client = new Google_Client();
$client->setDeveloperKey($apiKey);
$client->setClientId($clientID);
$client->setCLientSecret($clientSecret);
$client->setRedirectUri('http://vps441713.ovh.net/maxV2/youtubeAPI.php');
$client->setScopes('https://www.googleapis.com/auth/youtube');


$youtube = new Google_Service_YouTube($client);

session_start();

$loginUrl = $client->createAuthUrl();

if (isset($_GET['code'])) {
    $client->authenticate($_GET['code']);
    $_SESSION['token'] = $client->getAccessToken();
}

if (isset($_SESSION['token'])) {
    $client->setAccessToken($_SESSION['token']);
}


if ($client->getAccessToken()) {
    $snippet = new Google_Service_YouTube_VideoSnippet();
    $snippet->setTitle('Max Video Generation');
    $snippet->setDescription('A news based video, automatically generated by Max');
    $snippet->setTags(['automation','news','IA']);
    $snippet->setCategoryId(17);

    $status = new Google_Service_YouTube_VideoStatus(); 
    $status->setPrivacyStatus('private');
    

    $video = new Google_Service_YouTube_Video();
    $video->setSnippet($snippet);
    $video->setStatus($status);

    
    $client->setDefer(true);

    $request = $youtube->videos->insert("status,snippet", $video);

    // $file = dirname(__DIR__).'video.mp4';
    $filePath = '/var/www/html/maxV2/model/outputs/generated_video_final.mp4';

    $chunkSizeBytes = 1 * 1024 * 1024;


    // $media = new Google_Http_MediaFileUpload($client, $request, 'video/*', file_get_contents($file));
    $media = new Google_Http_MediaFileUpload(
        $client,
        $request,
        'video/*',
        null,
        true,
        $chunkSizeBytes
    );
    $media->setFileSize(filesize($filePath));

    //  Read the media file and upload it chunk by chunk.
    $status = false;
    $handle = fopen($filePath, "rb");
    while (!$status && !feof($handle)) {
      $chunk = fread($handle, $chunkSizeBytes);
      $status = $media->nextChunk($chunk);
    }

    fclose($handle);
    $client->setDefer(false);

    $access = true;

} else {
    
    $access = false;
    
}



// Displaying the view :
include_once('view/video_upload.php');